namespace TiaCodegen.Enums
{
    public enum SignalType
    {
        Bool,
        Byte,
        Int,
        SInt,
        DInt,
        UInt,
        UDInt,
        Time,
        UDT,
        String,
        Real,
        Constant,
        ConstantBool,
        ConstantInt,
        ConstantDInt,
        ConstantUInt,
        ConstantUDInt,
        ConstantTime,
        ConstantString,
        ConstantReal,
        ConstantWord,
        Custom,
        Void,
        Variant,
        ProgramAlarm,
        Word
    }
}
