export enum SignalType {
    Bool = 'Bool',
    Byte = 'Byte',
    Int = 'Int',
    DInt = 'DInt',
    UInt = 'UInt',
    UDInt = 'UDInt',
    Time = 'Time',
    UDT = 'UDT',
    String = 'String',
    Real = 'Real',
    Constant = 'Constant',
    ConstantBool = 'ConstantBool',
    ConstantInt = 'ConstantInt',
    ConstantDInt = 'ConstantDInt',
    ConstantUInt = 'ConstantUInt',
    ConstantUDInt = 'ConstantUDInt',
    ConstantTime = 'ConstantTime',
    ConstantString = 'ConstantString',
    ConstantReal = 'ConstantReal',
    ConstantWord = 'ConstantWord',
    Custom = 'Custom',
    Void = 'Void',
    Variant = 'Variant',
    ProgramAlarm = 'ProgramAlarm',
    Word = 'Word',
}
